title: 秋潺
description: 胡言乱语
keyword: '秋潺,博客,blog'
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://yvoly.github.io/' # the base hostname & protocol for your site, e.g. http://example.com

# About/contact
owner:秋潺
    name: '秋潺'

# Data
avatar: https://cdn.jsdelivr.net/gh/yvoly/yvoly@main/avatar.jpg
favicon: https://cdn.jsdelivr.net/gh/yvoly/yvoly@main/avatar.jpg

# Build settings
# use Github Flavored Markdown !important
# document: http://jekyllrb.com/docs/configuration/#kramdown

markdown: kramdown

highlighter: rouge
permalink: pretty
paginate: 16

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
    - .jekyll-cache/
    - gemfiles/
    - Gemfile
    - Gemfile.lock
    - README.md

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Gems
plugins: [jekyll-paginate]
